# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotGOT_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostedParty', to='gotGOT_app.User')),
                ('joiners', models.ManyToManyField(related_name='joinedParty', to='gotGOT_app.User')),
            ],
        ),
    ]
