# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gotGOT_app', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hosts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='gotGOT_app.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='joiners',
            field=models.ManyToManyField(related_name='joiners', to='gotGOT_app.User'),
        ),
    ]
